# coding: utf-8

# flake8: noqa
"""
    Lab 2 API made with love by Roman Kovalchuk

    variant №12  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.discipline import Discipline
from openapi_client.models.marks import Marks
from openapi_client.models.marks_list import MarksList
from openapi_client.models.rating import Rating
from openapi_client.models.rating_list import RatingList
from openapi_client.models.student import Student
