# coding: utf-8

"""
    Lab 2 API made with love by Roman Kovalchuk

    variant №12  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class Discipline(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'discipline_name': 'Varchar',
        'credits': 'int'
    }

    attribute_map = {
        'discipline_name': 'DisciplineName',
        'credits': 'Credits'
    }

    def __init__(self, discipline_name=None, credits=None, local_vars_configuration=None):  # noqa: E501
        """Discipline - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._discipline_name = None
        self._credits = None
        self.discriminator = None

        if discipline_name is not None:
            self.discipline_name = discipline_name
        if credits is not None:
            self.credits = credits

    @property
    def discipline_name(self):
        """Gets the discipline_name of this Discipline.  # noqa: E501


        :return: The discipline_name of this Discipline.  # noqa: E501
        :rtype: Varchar
        """
        return self._discipline_name

    @discipline_name.setter
    def discipline_name(self, discipline_name):
        """Sets the discipline_name of this Discipline.


        :param discipline_name: The discipline_name of this Discipline.  # noqa: E501
        :type: Varchar
        """

        self._discipline_name = discipline_name

    @property
    def credits(self):
        """Gets the credits of this Discipline.  # noqa: E501


        :return: The credits of this Discipline.  # noqa: E501
        :rtype: int
        """
        return self._credits

    @credits.setter
    def credits(self, credits):
        """Sets the credits of this Discipline.


        :param credits: The credits of this Discipline.  # noqa: E501
        :type: int
        """

        self._credits = credits

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Discipline):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Discipline):
            return True

        return self.to_dict() != other.to_dict()
