# coding: utf-8

"""
    Lab 2 API made with love by Roman Kovalchuk

    variant №12  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class RatingList(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'student_id': 'Varchar',
        'marks_id': 'Varchar'
    }

    attribute_map = {
        'student_id': 'StudentID',
        'marks_id': 'MarksID'
    }

    def __init__(self, student_id=None, marks_id=None, local_vars_configuration=None):  # noqa: E501
        """RatingList - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._student_id = None
        self._marks_id = None
        self.discriminator = None

        if student_id is not None:
            self.student_id = student_id
        if marks_id is not None:
            self.marks_id = marks_id

    @property
    def student_id(self):
        """Gets the student_id of this RatingList.  # noqa: E501


        :return: The student_id of this RatingList.  # noqa: E501
        :rtype: Varchar
        """
        return self._student_id

    @student_id.setter
    def student_id(self, student_id):
        """Sets the student_id of this RatingList.


        :param student_id: The student_id of this RatingList.  # noqa: E501
        :type: Varchar
        """

        self._student_id = student_id

    @property
    def marks_id(self):
        """Gets the marks_id of this RatingList.  # noqa: E501


        :return: The marks_id of this RatingList.  # noqa: E501
        :rtype: Varchar
        """
        return self._marks_id

    @marks_id.setter
    def marks_id(self, marks_id):
        """Sets the marks_id of this RatingList.


        :param marks_id: The marks_id of this RatingList.  # noqa: E501
        :type: Varchar
        """

        self._marks_id = marks_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RatingList):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RatingList):
            return True

        return self.to_dict() != other.to_dict()
