# coding: utf-8

"""
    Lab 2 API made with love by Roman Kovalchuk

    variant №12  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class Student(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'group': 'Varchar',
        'first_name': 'Varchar',
        'last_name': 'Varchar'
    }

    attribute_map = {
        'id': 'ID',
        'group': 'Group',
        'first_name': 'FirstName',
        'last_name': 'LastName'
    }

    def __init__(self, id=None, group=None, first_name=None, last_name=None, local_vars_configuration=None):  # noqa: E501
        """Student - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._group = None
        self._first_name = None
        self._last_name = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if group is not None:
            self.group = group
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name

    @property
    def id(self):
        """Gets the id of this Student.  # noqa: E501


        :return: The id of this Student.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Student.


        :param id: The id of this Student.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def group(self):
        """Gets the group of this Student.  # noqa: E501


        :return: The group of this Student.  # noqa: E501
        :rtype: Varchar
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this Student.


        :param group: The group of this Student.  # noqa: E501
        :type: Varchar
        """

        self._group = group

    @property
    def first_name(self):
        """Gets the first_name of this Student.  # noqa: E501


        :return: The first_name of this Student.  # noqa: E501
        :rtype: Varchar
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this Student.


        :param first_name: The first_name of this Student.  # noqa: E501
        :type: Varchar
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this Student.  # noqa: E501


        :return: The last_name of this Student.  # noqa: E501
        :rtype: Varchar
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this Student.


        :param last_name: The last_name of this Student.  # noqa: E501
        :type: Varchar
        """

        self._last_name = last_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Student):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Student):
            return True

        return self.to_dict() != other.to_dict()
