"""empty message

Revision ID: e7ae39ca3889
Revises: 
Create Date: 2020-12-05 22:54:32.594541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ae39ca3889'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('price', sa.REAL(), nullable=True),
    sa.Column('seat', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('ticket_id', sa.INTEGER(), nullable=True),
    sa.Column('booked', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('ticket')
    # ### end Alembic commands ###
