# coding: utf-8

# flake8: noqa

"""
    Lab 2 API made with love by Roman Kovalchuk

    variant №12  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.disciplines_api import DisciplinesApi
from openapi_client.api.marks_api import MarksApi
from openapi_client.api.rating_api import RatingApi
from openapi_client.api.student_api import StudentApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiException
# import models into sdk package
from openapi_client.models.discipline import Discipline
from openapi_client.models.marks import Marks
from openapi_client.models.marks_list import MarksList
from openapi_client.models.rating import Rating
from openapi_client.models.rating_list import RatingList
from openapi_client.models.student import Student

