# coding: utf-8

"""
    Lab 2 API made with love by Roman Kovalchuk

    variant №12  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.rating_api import RatingApi  # noqa: E501
from openapi_client.rest import ApiException


class TestRatingApi(unittest.TestCase):
    """RatingApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.rating_api.RatingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rating_get(self):
        """Test case for rating_get

        Returns current rating  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
