# coding: utf-8

"""
    Lab 2 API made with love by Roman Kovalchuk

    variant №12  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.disciplines_api import DisciplinesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDisciplinesApi(unittest.TestCase):
    """DisciplinesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.disciplines_api.DisciplinesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_disciplines_id_get(self):
        """Test case for disciplines_id_get

        """
        pass

    def test_disciplines_id_post(self):
        """Test case for disciplines_id_post

        New Discipline.  # noqa: E501
        """
        pass

    def test_disciplines_id_put(self):
        """Test case for disciplines_id_put

        update discipline.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
