# coding: utf-8

"""
    Lab 2 API made with love by Roman Kovalchuk

    variant №12  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.marks_api import MarksApi  # noqa: E501
from openapi_client.rest import ApiException


class TestMarksApi(unittest.TestCase):
    """MarksApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.marks_api.MarksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_marks_id_get(self):
        """Test case for marks_id_get

        return current student's marks.  # noqa: E501
        """
        pass

    def test_marks_id_post(self):
        """Test case for marks_id_post

        Assign a new Discipline to the student  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
