# coding: utf-8

"""
    Lab 2 API made with love by Roman Kovalchuk

    variant №12  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.marks_list import MarksList  # noqa: E501
from openapi_client.rest import ApiException

class TestMarksList(unittest.TestCase):
    """MarksList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MarksList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.marks_list.MarksList()  # noqa: E501
        if include_optional :
            return MarksList(
                discipline_id = 56, 
                mark = null, 
                passed = True
            )
        else :
            return MarksList(
        )

    def testMarksList(self):
        """Test MarksList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
